### ISSUE TITLE
Enable SetLooping

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/VideoPlayerPlugin#1]
https://github.com/tatfook/VideoPlayerPlugin/commit/b993fdb04fabe8cf9d999146e546c458e2229122
1.  需要支持下SetLooping, see above.  目前Seek会Crash

**Comment by hyz1992** [comment]
支持循环播放了：
https://github.com/tatfook/VideoPlayerPlugin/commit/90af711ab2c22d7c08bdfea446520f1b0565fb0c
Seek未观察到crash，是什么条件复现的？可以另开一个issue
