### ISSUE TITLE
exe not exit while video is playing

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/VideoPlayerPlugin#2]
视频播放时退出， paraengineclient.exe没有彻底关闭，

**Comment by hyz1992** [comment]
fixed in NPLRuntime: https://github.com/LiXizhi/NPLRuntime/pull/673
https://github.com/tatfook/VideoPlayerPlugin/commit/fc33431701f825c02d48cd9a26e374a952b2bfdd
